package com.pathshalapro.service.impl;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.pathshalapro.entity.Payment;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import com.pathshalapro.entity.FeeInvoice;
import com.pathshalapro.entity.FeeInvoiceItem;

@Slf4j
@Service
@RequiredArgsConstructor
public class PdfGeneratorService {

    private static final Color PRIMARY_COLOR = new Color(79, 70, 229); // Indigo 600
    private static final Color SECONDARY_COLOR = new Color(243, 244, 246); // Gray 100
    private static final Color TEXT_MUTED = new Color(107, 114, 128); // Gray 500

    private void addHeaderAndFooter(Document document) {
        // Footer
        Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9, TEXT_MUTED);
        HeaderFooter footer = new HeaderFooter(new Phrase("Generated by PathshalaPro | Support: support@pathshalapro.com | www.pathshalapro.com", footerFont), false);
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setBorder(Rectangle.TOP);
        footer.setBorderColor(TEXT_MUTED);
        document.setFooter(footer);
    }

    private void addBrandHeader(Document document, String documentTitle, String schoolName) throws DocumentException {
        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100);
        
        // Brand Name
        Font brandFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, PRIMARY_COLOR);
        PdfPCell brandCell = new PdfPCell(new Phrase("PathshalaPro", brandFont));
        brandCell.setBorder(Rectangle.NO_BORDER);
        brandCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        headerTable.addCell(brandCell);

        // Document Title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, TEXT_MUTED);
        PdfPCell titleCell = new PdfPCell(new Phrase(documentTitle.toUpperCase(), titleFont));
        titleCell.setBorder(Rectangle.NO_BORDER);
        titleCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        titleCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        headerTable.addCell(titleCell);

        document.add(headerTable);
        
        // Separator
        PdfPTable separator = new PdfPTable(1);
        separator.setWidthPercentage(100);
        separator.setSpacingBefore(10);
        separator.setSpacingAfter(20);
        PdfPCell sepCell = new PdfPCell();
        sepCell.setBorder(Rectangle.BOTTOM);
        sepCell.setBorderColor(PRIMARY_COLOR);
        sepCell.setBorderWidth(2);
        separator.addCell(sepCell);
        document.add(separator);
        
        // School Info
        Font schoolFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
        document.add(new Paragraph(schoolName, schoolFont));
        document.add(Chunk.NEWLINE);
    }

    public byte[] generatePaymentReceipt(Payment payment) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(document, out);
            
            addHeaderAndFooter(document);
            document.open();

            addBrandHeader(document, "Receipt", payment.getSchool().getName());

            Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11);
            Font mutedFont = FontFactory.getFont(FontFactory.HELVETICA, 10, TEXT_MUTED);

            // Details Section
            PdfPTable infoTable = new PdfPTable(2);
            infoTable.setWidthPercentage(100);
            infoTable.setSpacingAfter(20);

            // Left Col: Student Info
            PdfPCell leftCol = new PdfPCell();
            leftCol.setBorder(Rectangle.NO_BORDER);
            leftCol.addElement(new Paragraph("Billed To:", mutedFont));
            leftCol.addElement(new Paragraph(payment.getPaidBy().getFirstName() + " " + payment.getPaidBy().getLastName(), boldFont));
            leftCol.addElement(new Paragraph("Email: " + (payment.getPaidBy().getEmail() != null ? payment.getPaidBy().getEmail() : "N/A"), normalFont));
            infoTable.addCell(leftCol);

            // Right Col: Receipt Info
            PdfPCell rightCol = new PdfPCell();
            rightCol.setBorder(Rectangle.NO_BORDER);
            rightCol.addElement(new Paragraph("Receipt No: " + payment.getReceiptNumber(), boldFont));
            rightCol.addElement(new Paragraph("Date: " + payment.getPaymentDate(), normalFont));
            rightCol.addElement(new Paragraph("Invoice No: " + payment.getFeeInvoice().getInvoiceNumber(), normalFont));
            rightCol.addElement(new Paragraph("Transaction ID: " + payment.getRazorpayPaymentId(), normalFont));
            infoTable.addCell(rightCol);

            document.add(infoTable);

            // Payment Details Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10);
            table.setWidths(new float[]{7f, 3f});

            // Table Header
            PdfPCell cell1 = new PdfPCell(new Phrase("DESCRIPTION", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE)));
            cell1.setBackgroundColor(PRIMARY_COLOR);
            cell1.setPadding(8);
            cell1.setBorderColor(Color.WHITE);
            table.addCell(cell1);

            PdfPCell cell2 = new PdfPCell(new Phrase("AMOUNT (" + payment.getCurrency() + ")", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE)));
            cell2.setBackgroundColor(PRIMARY_COLOR);
            cell2.setPadding(8);
            cell2.setBorderColor(Color.WHITE);
            cell2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            table.addCell(cell2);

            // Table Content
            PdfPCell descCell = new PdfPCell(new Phrase("Fee Payment", normalFont));
            descCell.setPadding(10);
            descCell.setBorderColor(SECONDARY_COLOR);
            table.addCell(descCell);

            PdfPCell amtCell = new PdfPCell(new Phrase(payment.getAmount().toString(), normalFont));
            amtCell.setPadding(10);
            amtCell.setBorderColor(SECONDARY_COLOR);
            amtCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            table.addCell(amtCell);

            document.add(table);

            document.add(Chunk.NEWLINE);
            document.add(new Paragraph("Thank you for your payment.", FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 11, PRIMARY_COLOR)));

            document.close();
            return out.toByteArray();
        } catch (DocumentException | IOException e) {
            log.error("Failed to generate PDF receipt", e);
            throw new RuntimeException("Error generating receipt PDF");
        }
    }

    public byte[] generateInvoicePdf(FeeInvoice invoice) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(document, out);
            
            addHeaderAndFooter(document);
            document.open();

            addBrandHeader(document, "Invoice", invoice.getSchool().getName());

            Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11);
            Font mutedFont = FontFactory.getFont(FontFactory.HELVETICA, 10, TEXT_MUTED);

            // Details Section
            PdfPTable infoTable = new PdfPTable(2);
            infoTable.setWidthPercentage(100);
            infoTable.setSpacingAfter(20);

            // Left Col: Student Info
            PdfPCell leftCol = new PdfPCell();
            leftCol.setBorder(Rectangle.NO_BORDER);
            leftCol.addElement(new Paragraph("Invoice To:", mutedFont));
            leftCol.addElement(new Paragraph(invoice.getStudent().getFirstName() + " " + invoice.getStudent().getLastName(), boldFont));
            leftCol.addElement(new Paragraph("Admission No: " + invoice.getStudent().getAdmissionNo(), normalFont));
            infoTable.addCell(leftCol);

            // Right Col: Invoice Info
            PdfPCell rightCol = new PdfPCell();
            rightCol.setBorder(Rectangle.NO_BORDER);
            rightCol.addElement(new Paragraph("Invoice No: " + invoice.getInvoiceNumber(), boldFont));
            rightCol.addElement(new Paragraph("Date: " + invoice.getCreatedAt().toLocalDate(), normalFont));
            rightCol.addElement(new Paragraph("Due Date: " + invoice.getDueDate(), normalFont));
            
            Font statusFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, invoice.getPaymentStatus().equals("PAID") ? new Color(16, 185, 129) : new Color(245, 158, 11));
            rightCol.addElement(new Paragraph("Status: " + invoice.getPaymentStatus(), statusFont));
            infoTable.addCell(rightCol);

            document.add(infoTable);

            // Invoice Items Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10);
            table.setWidths(new float[]{7f, 3f});

            // Table Header
            PdfPCell cell1 = new PdfPCell(new Phrase("DESCRIPTION", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE)));
            cell1.setBackgroundColor(PRIMARY_COLOR);
            cell1.setPadding(8);
            cell1.setBorderColor(Color.WHITE);
            table.addCell(cell1);

            PdfPCell cell2 = new PdfPCell(new Phrase("AMOUNT (INR)", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE)));
            cell2.setBackgroundColor(PRIMARY_COLOR);
            cell2.setPadding(8);
            cell2.setBorderColor(Color.WHITE);
            cell2.setHorizontalAlignment(Element.ALIGN_RIGHT);
            table.addCell(cell2);

            // Items
            for (FeeInvoiceItem item : invoice.getItems()) {
                PdfPCell descCell = new PdfPCell(new Phrase(item.getFeeHead().getName(), normalFont));
                descCell.setPadding(8);
                descCell.setBorderColor(SECONDARY_COLOR);
                table.addCell(descCell);

                PdfPCell amtCell = new PdfPCell(new Phrase(item.getAmount().toString(), normalFont));
                amtCell.setPadding(8);
                amtCell.setBorderColor(SECONDARY_COLOR);
                amtCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                table.addCell(amtCell);
            }

            // Summary section
            if (invoice.getDiscountAmount().compareTo(java.math.BigDecimal.ZERO) > 0) {
                PdfPCell lbl = new PdfPCell(new Phrase("Discount", normalFont));
                lbl.setHorizontalAlignment(Element.ALIGN_RIGHT);
                lbl.setPadding(8);
                lbl.setBorderColor(SECONDARY_COLOR);
                table.addCell(lbl);
                
                PdfPCell val = new PdfPCell(new Phrase("-" + invoice.getDiscountAmount().toString(), normalFont));
                val.setHorizontalAlignment(Element.ALIGN_RIGHT);
                val.setPadding(8);
                val.setBorderColor(SECONDARY_COLOR);
                table.addCell(val);
            }
            if (invoice.getFineAmount().compareTo(java.math.BigDecimal.ZERO) > 0) {
                PdfPCell lbl = new PdfPCell(new Phrase("Late Fee / Fine", normalFont));
                lbl.setHorizontalAlignment(Element.ALIGN_RIGHT);
                lbl.setPadding(8);
                lbl.setBorderColor(SECONDARY_COLOR);
                table.addCell(lbl);
                
                PdfPCell val = new PdfPCell(new Phrase(invoice.getFineAmount().toString(), normalFont));
                val.setHorizontalAlignment(Element.ALIGN_RIGHT);
                val.setPadding(8);
                val.setBorderColor(SECONDARY_COLOR);
                table.addCell(val);
            }
            
            // Total
            PdfPCell totalDescCell = new PdfPCell(new Phrase("Total Amount", boldFont));
            totalDescCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            totalDescCell.setPadding(8);
            totalDescCell.setBackgroundColor(SECONDARY_COLOR);
            totalDescCell.setBorderColor(Color.WHITE);
            table.addCell(totalDescCell);
            
            PdfPCell totalValCell = new PdfPCell(new Phrase(invoice.getNetAmount().toString(), boldFont));
            totalValCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            totalValCell.setPadding(8);
            totalValCell.setBackgroundColor(SECONDARY_COLOR);
            totalValCell.setBorderColor(Color.WHITE);
            table.addCell(totalValCell);

            // Paid
            PdfPCell paidDescCell = new PdfPCell(new Phrase("Paid Amount", boldFont));
            paidDescCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            paidDescCell.setPadding(8);
            paidDescCell.setBorderColor(SECONDARY_COLOR);
            table.addCell(paidDescCell);
            
            PdfPCell paidValCell = new PdfPCell(new Phrase(invoice.getPaidAmount().toString(), boldFont));
            paidValCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            paidValCell.setPadding(8);
            paidValCell.setBorderColor(SECONDARY_COLOR);
            table.addCell(paidValCell);

            // Balance
            java.math.BigDecimal balance = invoice.getNetAmount().subtract(invoice.getPaidAmount());
            PdfPCell balDescCell = new PdfPCell(new Phrase("Balance Due", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, PRIMARY_COLOR)));
            balDescCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            balDescCell.setPadding(8);
            balDescCell.setBorderColor(SECONDARY_COLOR);
            table.addCell(balDescCell);
            
            PdfPCell balValCell = new PdfPCell(new Phrase(balance.toString(), FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, PRIMARY_COLOR)));
            balValCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            balValCell.setPadding(8);
            balValCell.setBorderColor(SECONDARY_COLOR);
            table.addCell(balValCell);

            document.add(table);

            document.add(Chunk.NEWLINE);
            document.add(new Paragraph("Please pay the due amount before the due date to avoid late fees.", FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, TEXT_MUTED)));

            document.close();
            return out.toByteArray();
        } catch (DocumentException | IOException e) {
            log.error("Failed to generate PDF invoice", e);
            throw new RuntimeException("Error generating invoice PDF");
        }
    }
}

